# Generated by Django 3.2.1 on 2021-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantidade_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
