# Generated by Django 3.2.1 on 2021-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210527_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantidade_vendas',
            field=models.IntegerField(default=0, verbose_name='Quantidades de vendas'),
        ),
    ]
