# Generated by Django 3.2.1 on 2021-05-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('Parcelado em 180', 'parcelado'), ('À vista', 'avista')], max_length=255, verbose_name='Forma de pagamento'),
        ),
    ]
