# Generated by Django 3.2.1 on 2021-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_venda_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('parcelado', 'Parcelado em 180'), ('avista', ' À vista')], max_length=255, verbose_name='Forma de pagamento'),
        ),
    ]
