# Generated by Django 3.2.1 on 2021-05-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_venda_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='venda_status',
            field=models.BooleanField(default=False),
        ),
    ]
