# Generated by Django 3.2.1 on 2021-05-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venda_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
