# Generated by Django 3.2.1 on 2021-05-09 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_venda_cliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='vendedor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_user', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
