# Generated by Django 3.2.1 on 2021-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_venda_vendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='vendido_status',
            field=models.BooleanField(default=False),
        ),
    ]
