# Generated by Django 3.2.1 on 2021-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imovel_vendido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='quantidade_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
