# Generated by Django 3.2.1 on 2021-05-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_quantidade_vendas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='quantidade_vendas',
            new_name='quantidade_compras',
        ),
        migrations.AddField(
            model_name='imovel',
            name='propretario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
    ]
