# Generated by Django 3.2.1 on 2021-05-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210509_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='propretario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
    ]
