# Generated by Django 3.2.1 on 2021-05-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_imovel_propretario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
